config/routes.rb
Rails.application.routes.draw do
  root to: 'index#introduction'
  get 'form', to:'maches#index'
  get 'mychart', to:'maches#index'
  get 'totalchart', to:'maches#index'

  get 'links/index', to:'maches#index'
  get 'master/index', to:'master#index'

  get 'links/:kc/form', to:'maches#form'
  post 'links/:kc/form', to:'maches#create'
  get 'links/:kc/sended_form', to:'maches#sended_form'
  get 'links/:kc/mychart', to:'maches#mychart'
  get 'links/:kc/mychart/my_duel_data.csv', to:'maches#mydata_csv'
  get 'links/:kc/totalchart', to:'maches#totalchart'
  get 'links/:kc/edit/:id', to: 'maches#edit'
  patch 'links/:kc/edit/:id', to: 'maches#update'
  get 'links/:kc/delete/:id', to:'maches#delete'
  get 'links/:kc/:deck', to:'maches#deckchart'

  get 'master/:dc/form', to:'master#form'
  post 'master/:dc/form', to:'master#create'
  get 'master/:dc/sended_form', to:'master#sended_form'
  get 'master/:dc/mychart', to:'master#mychart'
  get 'master/:dc/mychart/my_duel_data.csv', to:'master#mydata_csv'
  get 'master/:dc/totalchart', to:'master#totalchart'
  get 'master/:dc/edit/:id', to: 'master#edit'
  patch 'master/:dc/edit/:id', to: 'master#update'
  get 'master/:dc/delete/:id', to:'master#delete'
  get 'master/:dc/close', to:'master#close'
  
  get 'admin/export', to:'admin#export'
  get 'admin/export/accounts.csv', to:'admin#export_accounts'
  get 'admin/export/matches.csv', to:'admin#export_matches'
  get 'admin/user_list', to:'admin#user_list'
  get 'admin/inquiry_list', to:'admin#inquiry_list'
  get 'admin/inquiry/delete/:id', to:'admin#inquiry_delete'

  post 'select_kc', to:'maches#select_kc'
  post 'select_datetime', to:'maches#select_datetime'
  post 'select_dprange', to:'maches#select_dprange'

  get 'past_kc', to:'index#past_kc'
  get 'past_kc/:kcname', to:'index#past_kc_chart'
  
  devise_for :accounts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- Google Adsence -->
    <script data-ad-client="ca-pub-4383624542979357" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    
    <title>KC Chart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>

    <!-- amCharts javascript sources -->
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/pie.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/serial.js"></script>

    <style>
    h1{
        font-family: 'SmartFontUI';
    }
    </style>

</head>

<body>

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/mychart">
        <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-chart-pie"></i>
        </div>
        <div class="sidebar-brand-text mx-3">KC Chart</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Heading -->
    <div class="sidebar-heading">
        Pages
    </div>

    <!-- Nav Item -->
    <li class="nav-item">
        <a class="nav-link" href="/admin/export/">
        <span>Export</span></a>
    </li>

    <!-- Nav Item -->
    <li class="nav-item">
        <a class="nav-link" href="/admin/user_list/">
        <span>User List</span></a>
    </li>

    <!-- Nav Item -->
    <li class="nav-item">
        <a class="nav-link" href="/admin/inquiry_list/">
        <span>Inquiry List</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    </ul>
    <!-- End of Sidebar -->
    
    <script>
    <!-- 画面幅が小さいときにサイドバー隠す -->
    $(document).ready(function(){
        if ($(window).width() < 576 && !$(".sidebar").hasClass("toggled")) {
        $("body").addClass("sidebar-toggled");
        $(".sidebar").addClass("toggled");
        $('.sidebar .collapse').collapse('hide');
        };  
    });

    <!-- 現在のナビゲーションをアクティブにする -->
    $(document).ready(function() {
        if(location.pathname != "/") {
        var $path = location.href.split('/');
        var $endPath = $path.slice($path.length-2,$path.length-1);
        $('ul#accordionSidebar li a[href$="'+$endPath+'/"]').parent().addClass('active');
        }
    });
    </script>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for...(Unimplemented)" aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
        </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
        <%= yield %>
        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <div>
            <a href="/privacy_policy/">プライバシーポリシー</a>&nbsp;|&nbsp;
            <a href="/inquiry/">お問い合わせフォーム</a>
            </div>
            <%= link_to('ログアウト', destroy_account_session_path, :method => :delete) %>
        </div>
        </div>
    </footer>
    <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Custom scripts for all pages-->
<script src="/assets/sb-admin-2/sb-admin-2.js"></script>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- Google AdSense -->
    <script data-ad-client="ca-pub-3750978027025894" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MEL7W52L9D"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-MEL7W52L9D');
    </script>
    
    <title>KC Chart</title>
    <%= favicon_link_tag('favicon.ico') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= include_gon %>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>
</head>

<body>

<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light topbar static-top" style="background-color: #4E73DF">

        <!-- Title -->
        <a class="navbar-brand d-none d-sm-flex align-items-center justify-content-center pl-2" href="/">
                <%= image_tag asset_path("logo/logo2-2.png"), :height =>"48px" %>
                <div class="index-title pb-1 text-white">KC Chart</div>
        </a>
        <a class="navbar-brand d-sm-none align-items-center justify-content-center pl-4" href="/">
                <%= image_tag asset_path("logo/logo2-2.png"), :height =>"48px"%>
        </a>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- ログイン -->
            <%= link_to "新規登録", new_account_registration_path, class: 'btn btn-light' %>
            &nbsp;&nbsp;
            <%= link_to "ログイン", new_account_session_path, class: 'btn btn-outline-light' %>
        </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid px-0">
        <%= yield %>
        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <div>
            <a href="/privacy_policy/">プライバシーポリシー</a>&nbsp;|&nbsp;
            <a href="/inquiry/">お問い合わせフォーム</a>
            </div>
            <label></label>
        </div>
        </div>
    </footer>
    <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Custom scripts for all pages-->
<script src="/assets/sb-admin-2/sb-admin-2.js"></script>

</body>
</html>

app/views/layouts/inquiry.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- Google Adsence -->
    <script data-ad-client="ca-pub-4383624542979357" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    
    <title>KC Chart</title>
    <%= favicon_link_tag('favicon.ico') %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>

    <!-- amCharts javascript sources -->
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/pie.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/serial.js"></script>

    <style>
    h1{
        font-family: 'SmartFontUI';
    }
    </style>

</head>

<body>

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/mychart">
        <%= image_tag asset_path("logo/logo2-2.png"), :height =>"40px" %>
        <div class="sidebar-brand-text mx-3">KC Chart</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Heading -->
    <div class="sidebar-heading">
        Pages
    </div>

    <!-- Nav Item - Form -->
    <li class="nav-item">
        <a class="nav-link" href="/form/">
        <i class="fas fa-fw fa-paper-plane"></i>
        <span>Record</span></a>
    </li>

    <!-- Nav Item - My Charts -->
    <li class="nav-item">
        <a class="nav-link" href="/mychart/">
        <i class="fas fa-fw fa-user"></i>
        <span>My Page</span></a>
    </li>

    <!-- Nav Item - Total Charts -->
    <li class="nav-item">
        <a class="nav-link" href="/totalchart">
        <i class="fas fa-fw fa-users"></i>
        <span>Total Page</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    </ul>
    <!-- End of Sidebar -->
    
    <script>
    <!-- 画面幅が小さいときにサイドバー隠す -->
    $(document).ready(function(){
        if ($(window).width() < 576 && !$(".sidebar").hasClass("toggled")) {
        $("body").addClass("sidebar-toggled");
        $(".sidebar").addClass("toggled");
        $('.sidebar .collapse').collapse('hide');
        };  
    });

    <!-- 現在のナビゲーションをアクティブにする -->
    $(document).ready(function() {
        if(location.pathname != "/") {
        var $path = location.href.split('/');
        var $endPath = $path.slice($path.length-2,$path.length-1);
        $('ul#accordionSidebar li a[href$="'+$endPath+'/"]').parent().addClass('active');
        }
    });
    </script>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for...(Unimplemented)" aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
        </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
        <%= yield %>
        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <div>
            <a href="/privacy_policy/">プライバシーポリシー</a>&nbsp;|&nbsp;
            <a href="/inquiry/">お問い合わせフォーム</a>
            </div>
            <%= link_to('ログアウト', destroy_account_session_path, :method => :delete) %>
        </div>
        </div>
    </footer>
    <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Custom scripts for all pages-->
<script src="/assets/sb-admin-2/sb-admin-2.js"></script>

</body>
</html>

app/views/layouts/master.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google AdSense -->
    <script data-ad-client="ca-pub-3750978027025894" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MEL7W52L9D"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-MEL7W52L9D');
    </script>
    
    <title>KC Chart</title>
    <%= favicon_link_tag('favicon.ico') %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= include_gon %>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>

    <!-- amCharts javascript sources -->
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/pie.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/serial.js"></script>

    <!-- hierarchy-select -->
    <%= javascript_include_tag asset_path("hierarchy-select/hierarchy-select.min.js") %>

    <style>
      .table-fixed th:first-child, td:first-child {
        position: sticky;  position: -webkit-sticky;
        left: 0;
      }
      .table-fixed tr:nth-of-type(odd) th:first-child {
        background-color: #fff;
      }
      .table-fixed tr:nth-of-type(odd) td:first-child {
        background-color: #fff;
      }
      .table-fixed tr:nth-of-type(even) td:first-child {
        background-color: #fff;
      }

      .table-compatibility td{
        height: 64px;
        padding: 0px;
        vertical-align: middle;
        text-align: center;
      }

      .table-matchresult td{
        height: 48px;
        padding: 0px 10px;
        vertical-align: middle;
      }

      .table-skilllist td{
        height: 64px;
        padding: 0px 10px;
        vertical-align: middle;
        text-align: center;
      }

      #pibot-mydeck {
        vertical-align: top;
      }

      h1{
        font-family: 'SmartFontUI';
      }
    </style>
  
  </head>

  <body>

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/master/<%= dc() %>/mychart">
        <%= image_tag asset_path("logo/logo2-2.png"), :height =>"40px" %>
        <div class="sidebar-brand-text mx-3">KC Chart</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Heading -->
      <div class="sidebar-heading">
        Pages
      </div>

      <!-- Nav Item - Form -->
      <li class="nav-item">
        <a class="nav-link" href="/master/<%= dc() %>/form">
          <i class="fas fa-fw fa-paper-plane"></i>
          <span>Record</span></a>
      </li>

      <!-- Nav Item - My Charts -->
      <li class="nav-item">
        <a class="nav-link" href="/master/<%= dc() %>/mychart">
          <i class="fas fa-fw fa-user"></i>
          <span>My Page</span></a>
      </li>

      <!-- Nav Item - Total Charts -->
      <li class="nav-item">
        <a class="nav-link" href="/master/<%= dc() %>/totalchart">
          <i class="fas fa-fw fa-users"></i>
          <span>Total Page</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->
    
    <script>
      <!-- 画面幅が小さいときにサイドバー隠す -->
      $(document).ready(function(){
        if ($(window).width() < 576 && !$(".sidebar").hasClass("toggled")) {
          $("body").addClass("sidebar-toggled");
          $(".sidebar").addClass("toggled");
          $('.sidebar .collapse').collapse('hide');
        };  
      });

      <!-- 現在のナビゲーションをアクティブにする -->
      $(document).ready(function() {
        var path = location.pathname.split('/');
        var endPath = path[path.length-1];
        $('ul#accordionSidebar li a[href$="./'+endPath+'"]').parent().addClass('active');
      });
    </script>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- DC選択 -->
            <div class="dropdown">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="kc-dropdown"><%= dc() %></button>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><button class="dropdown-item select_kc_master" value="DC2022Aug">DC2022Aug</button></li>
                <li><button class="dropdown-item select_kc_master" value="DC2022Dec">DC2022Dec</button></li>
                <li><button class="dropdown-item select_kc_master" value="DC2023Mar">DC2023Mar</button></li>
                <li><button class="dropdown-item select_kc_master" value="DC2023May">DC2023May</button></li>
                <li><button class="dropdown-item select_kc_master" value="DC2023Oct">DC2023Oct</button></li>
                <li><button class="dropdown-item select_kc_links" value="">DuelLinksへ</button></li>
              </ul>
            </div>
            <button type="button" class="btn btn-outline-primary" id="searchButton" data-toggle="modal" data-target="#searchModal">絞り込み</button>

            <script>
              <!-- DC選択のスクリプト -->
              $(function(){
                $('.select_kc_links').click(function(){
                  location.search = "";
                  location.pathname = 'links/index';
                })
                $('.select_kc_master').click(function(){
                  var path = location.pathname.split('/');
                  var endPath = path[path.length-1];
                  location.search = "";
                  location.pathname = 'master/' + $(this).attr('value') + '/' + endPath;
                })
              });
            </script>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          <%= yield %>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <div>
              お問い合わせは&nbsp;
              <a href="https://twitter.com/conconClasher">私のTwitter</a>&nbsp;へ
              </div>
            <%= link_to('ログアウト', destroy_account_session_path, :method => :delete) %>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- モーダルの設定 -->
  <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="searchModalLabel">絞り込み</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
          <h4>先後</h4>
          <div class="form-group">
            <div class="tab-wrap">
              <% if @order == "first" %>
                <input type="checkbox" id="checkbox_first" class="tab-switch" checked><label class="tab-label1" for="checkbox_first">先行</label>
              <% else %>
                <input type="checkbox" id="checkbox_first" class="tab-switch"><label class="tab-label1" for="checkbox_first">先行</label>
              <% end %>
              <% if @order == "second" %>
                <input type="checkbox" id="checkbox_second" class="tab-switch" checked><label class="tab-label2" for="checkbox_second">後攻</label>
              <% else %>
                <input type="checkbox" id="checkbox_second" class="tab-switch"><label class="tab-label2" for="checkbox_second">後攻</label>
              <% end %>
            </div>
          </div>
          <br>
          <h4>DP</h4>
          Min
          <input type="number" id="dpMin" class="form-control" value=<%= @dpMin != nil ? @dpMin : "" %>>
          Max
          <input type="number" id="dpMax" class="form-control" value=<%= @dpMax != nil ? @dpMax : "" %>>
          <br><br>
          <h4>時刻</h4>
          Min
          <input type="datetime-local" id="timeMin" class="form-control" min=<%= @TIMEMIN %> max=<%= @TIMEMAX %> value=<%= @timeMin != nil ? @timeMin : @TIMEMIN %>>
          Max
          <input type="datetime-local" id="timeMax" class="form-control" min=<%= @TIMEMIN %> max=<%= @TIMEMAX %> value=<%= @timeMax != nil ? @timeMax : @TIMEMAX %>>
        </div>
        <div class="modal-footer">
          <button type="button" id="reset" class="btn btn-secondary">リセット</button>
          <button type="button" id="search" class="btn btn-primary">検索</button>
        </div><!-- /.modal-footer -->
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <script>
    $(function(){
      $('#search').click(function(){
        search = 'dpMin='+$('#dpMin').val()+'&dpMax='+$('#dpMax').val()+'&timeMin='+$('#timeMin').val()+'&timeMax='+$('#timeMax').val();
        if(checkbox_first.checked && !checkbox_second.checked){
          search = search + "&order=first";
        }
        if(!checkbox_first.checked && checkbox_second.checked){
          search = search + "&order=second";
        }
        location.search = search;
      })
      $('#reset').click(function(){
        location.search = "";
      })
    });
  </script>

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Custom scripts for all pages-->
  <script src="/assets/sb-admin-2/sb-admin-2.js"></script>

  </body>
</html>